spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/northface
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: denrax
    password: denrax
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 50MB

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
  servlet:
    context-path: /api/v1/

springdoc:
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: dAKb1XHWuQ4KgutGuhazhegdhAd=
      expiration: 864000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account