services:
  postgres:
    image: postgres:latest
    container_name: north-faceMicroservice-db
    environment:
      POSTGRES_PASSWORD: "password123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "northface"
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local