spring:
  profiles:
    active: dev
  application:
    name: users
  servlet:
    multipart:
      max-file-size: 50MB
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  servelet:
    context-path: api/v1
  port: 8090

springdoc:
  default-produces-media-type: application/json

application:
  config:
    user-url: http://8092/api/vi/products